### ISSUE TITLE
Create an IPYNB for ARIMAX, SARIMAX AND LSTM  for time series forecasting.

### ISSUE THREAD

**Issue by kganeshv12** [kganeshv12/Time_series_analysis#2]
Use Augmented Dicky-Fuller test to find test statistic for ARIMAX & SARIMAX values.
For LSTMs use the MAE and MAPE loss metrics .
Plot graphs wherever necessary.

**Comment by LeShaurya** [comment]
please assign me this @kganeshv12 .
